Code Review
dev1980/DESIGN-TEARDOWN pull request #1
Opened 2019-08-01 22:25 UTC by David405

I believe this is ready for code review

2019-08-02 02:48 UTC, Ispirett commented
# Reviewing

2019-08-02 03:15 UTC, Ispirett requested changes
Hey, folks great work with this project you are doing a fantastic job. There are just a few changes that Mircoverse requires before this project can be completed.

* [ ] Every child of  `<section>` should be an `<article>` HTML tag . Instead of using div's inside of you `<section>` tags use the `<article`>
- [ ]  This section is missing 
![smashing](https://user-images.githubusercontent.com/38801423/62341354-fdfd7200-b4b0-11e9-9104-0edd4bfc2590.png)

- [ ] Also Please try to get your layout of the site to look more like the original website.
Some sections are either in the wrong place or missing. For example.

![wrong_place](https://user-images.githubusercontent.com/38801423/62341591-ebd00380-b4b1-11e9-8bf5-f7a1cfcdbb32.png)

This should be right before the footer.

2019-08-02 03:15 UTC, Ispirett commented on index.html
> +            <div class="navbar">
## Navigation bar
- [ ]  Should use the <nav> HTML tag instead of div
- [ ]  Should have seven separate containers (<div> is recommended). You should use <div> instead of the **ul and li** 
- [ ] Th **div's**  should be positioned using the float or flex display properties

2019-08-02 03:15 UTC, Ispirett commented on index.html
> +    <header>
All content should be wrapped with `<main>` HTML tags

2019-08-02 03:15 UTC, Ispirett commented on index.html
> +                    <ul>
The li items inside the `<ul>` tags should be positioned using the float or flex display property.

2019-08-03 03:23 UTC, bolah2009 commented
Currently under review

2019-08-03 03:27 UTC, bolah2009 commented
## Nice Job Team :clap:  

The [clone](https://raw.githack.com/dev1980/DESIGN-TEARDOWN/feature-branch/index.html) looks good to me and shows the use of visual hierarchy and typography. :+1: 

#### Consider checking out the comments and [these errors](https://validator.w3.org/nu/?doc=https%3A%2F%2Fraw.githack.com%2Fdev1980%2FDESIGN-TEARDOWN%2Ffeature-branch%2Findex.html) on using `h1` as top-level heading only and using an heading (h2-h6) element in an `<article>` and `<section>` elelment before merging.

Good luck with your next project. :star2: 

Cheers
[Bola](https://bolabuari.com/)

2019-08-05 15:22 UTC, merged

2019-08-05 15:22 UTC, dev1980 commented
All error fixed.